version: "3"

services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./:/app

  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

volumes:
  postgres_data:
