version: "3"

services:
  bot:
    build: .
    env_file:
      - ./.env
    volumes:
      - ./:/app

  # postgres:
  #   image: postgres:alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=nagatoro
  #     - POSTGRES_USER=nagatoro
  #     - POSTGRES_PASSWORD=nagatoro

# volumes:
#   postgres_data:
