"""Add MapSegment model

Revision ID: b838b77e92a0
Revises: ab031a6ffc11
Create Date: 2023-08-04 19:18:47.493526+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b838b77e92a0"
down_revision = "ab031a6ffc11"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map_segment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile"], ["profile.id"], name="fk_map_segment_profile_id_profile"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile", "number", name="uc_map_segment_profile_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("map_segment")
    # ### end Alembic commands ###
